### ISSUE TITLE
Setting "destroy leaves" to false causes a game crash

### ISSUE THREAD

**Issue by swayyger** [Invadermonky/Timber-Tree_Felling#2]
Hello, I'm specifically using version 1.1.0 of the mod.
Title really says it all, if you set destroy leaves to false in the mod config, the game crashes when you try to break a log while holding an axe. Any log causes this crash, whether it's part of a tree or a building.
I created a new mod profile with only this mod installed and the crash still occurred so I'm certain it wasn't because of an incompatibility with another mod. I did not edit any of the other configs, either.
When the game crashes, it gives exit code -805306369. Not sure if that has any significance, but I figured I should add it in.

**Comment by Invadermonky** [comment]
Sorry, I haven't had a lot of time recently. I'm working on a newer version that is changing the way the mod actually works and am probably going to remove the leaf breaking functionality since other mods usually handle it better (such as fast leaf decay).

**Comment by Invadermonky** [comment]
Setting removed as of version 1.12.2-1.2.0

Issue will be marked as Closed.
